### ISSUE TITLE
Need Ferret Facts

### ISSUE THREAD

**Issue by gvn96** [kinduff/dog-api#2]
You claim to need an equilibrium in the pet fact world. 
However, I have noticed that you do not have a ferret facts app. 
I would ask that you kindly consider cloning your source for this app 
and simply replacing the dog facts with ferret facts. I will provide a link
to many pre-compiled ferret facts for you use. 

If you are able to incorporate this, you would help me fulfill the life long dream 
of driving a co-worker absolutely nuts! 

https://www.lovethatpet.com/small-pets/ferrets/fun-facts/

https://www.factretriever.com/ferret-facts

**Comment by kinduff** [comment]
Would love to work on this but I don't have time at the moment. Feel free to fork and deploy, I'll be happy to assist you if you have any trouble.
