### ISSUE TITLE
dog-api.kinduff.com endpoint has expired certificate

### ISSUE THREAD

**Issue by anirbanmu** [kinduff/dog-api#4]
Looks like the cert expired on Janurary 8, 2018. Mostly just letting you know.

**Comment by kinduff** [comment]
Thanks for the report @anirbanmu looks like the autorenew failed due to an incident with Let's Encrypt (TLS-SNI-01 validation https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996). As soon as the service is up again, I'll renew manually.

**Comment by kinduff** [comment]
@anirbanmu issue has been resolved (it was a pain), it now returns a valid certificate. Thank you.
