### ISSUE TITLE
Discussion: Dog facts are sadder than cat facts

### ISSUE THREAD

**Issue by RoryDuncan** [kinduff/dog-api#5]
Compared to Cat Facts, dog facts seems to have more depressing, or less 'fun' of facts, generally dealing with dog homelessness, bite incidences, etc.

Cat Facts seem to be more playful.

**Comment by kinduff** [comment]
+1, this is a valid point. I would love to update the facts with new ones also, do you have any suggestion of where can I find these ones?

**Comment by RoryDuncan** [comment]
I'm not positive on where to find dog facts, either.

Perhaps introduce a web page to enter them--or a Google Form--and allow it to be populated with facts? 
The above introduces the possibility and likelihood of misinformation if not fact-checked but I imagine it could generate a solid amount. 🤔 

[Here's a handful coworkers researched and found today](https://docs.google.com/document/d/14E45fOVHICGSSsZo3apnqxWyJLWd3t21IQu7uyPCehk/edit?usp=sharing), disregard the typos.

**Comment by kinduff** [comment]
@RoryDuncan Thanks a lot for this! I will be updating as soon as I can, I'll be searching for funny/happier ones too. I'll keep you posted.

**Comment by kinduff** [comment]
@RoryDuncan Well, this is embarrassing. It took me 2 years to add your facts. I'm upgrading the app, thanks a lot for your contribution.

**Comment by RoryDuncan** [comment]
No worries! Thanks for putting the work in! :tada:
