### ISSUE TITLE
[Suggestion] Add parameter for raw returning of the fact

### ISSUE THREAD

**Issue by Evanito** [kinduff/dog-api#8]
For use with a chatbot on twitch that doesn't support parsing JSON, it would be useful if we could pass a parameter with our request such as `?raw=True` to just get the fact.

Example:
Current: `https://dog-api.kinduff.com/api/facts`
`{"facts":["More than 5,000,000 puppies are born in the U.S. every year."],"success":true}`

With flag: `https://dog-api.kinduff.com/api/facts?raw=True`
`More than 5,000,000 puppies are born in the U.S. every year.`

Also shoutout from dogdog 🐶

**Comment by danyalasif** [comment]
I'm writing Ruby for the first time and also trying to contribute code. 

I've added the `raw` param to `facts` endpoint. Let me know if it's correct. 👍

**Comment by kinduff** [comment]
Change is now deployed.
